apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-docker
  namespace: backend-api
  labels:
    app: backend-docker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-docker
  template:
    metadata:
      labels:
        app: backend-docker
    spec:
      containers:
      - name: backend-app
        image: el1coder/backend-docker-image:replaceImageTag
        ports:
        - containerPort: 3000
