apiVersion: v1
kind: Service
metadata:
  name: backend-docker-service
  namespace: backend-api
spec:
  selector:
    app: backend-docker
  ports:
    - protocol: TCP
      port: 80        
      targetPort: 3000 
  type: LoadBalancer
